/** TradingView public-widget "symbol" values for the lightweight chart and the
 * news timeline. OANDA is preferred for forex / metals (best free streaming
 * coverage); crypto routes to COINBASE / BITSTAMP / BINANCE depending on which
 * exchange exposes the pair on the free TradingView feed. Fallback for any
 * unknown symbol is `OANDA:<SYMBOL>` since most forex tickers resolve there. */
export const TRADINGVIEW_SYMBOL_MAP: Record<string, string> = {
  // ── Forex (majors + crosses) — OANDA ──
  EURUSD: 'OANDA:EURUSD', GBPUSD: 'OANDA:GBPUSD', USDJPY: 'OANDA:USDJPY',
  USDCHF: 'OANDA:USDCHF', AUDUSD: 'OANDA:AUDUSD', NZDUSD: 'OANDA:NZDUSD',
  USDCAD: 'OANDA:USDCAD', EURGBP: 'OANDA:EURGBP', EURJPY: 'OANDA:EURJPY',
  GBPJPY: 'OANDA:GBPJPY', AUDJPY: 'OANDA:AUDJPY', NZDJPY: 'OANDA:NZDJPY',
  EURAUD: 'OANDA:EURAUD', EURNZD: 'OANDA:EURNZD', EURCHF: 'OANDA:EURCHF',
  GBPAUD: 'OANDA:GBPAUD', GBPNZD: 'OANDA:GBPNZD', GBPCHF: 'OANDA:GBPCHF',
  GBPCAD: 'OANDA:GBPCAD', AUDNZD: 'OANDA:AUDNZD', AUDCAD: 'OANDA:AUDCAD',
  AUDCHF: 'OANDA:AUDCHF', NZDCAD: 'OANDA:NZDCAD', NZDCHF: 'OANDA:NZDCHF',
  CADCHF: 'OANDA:CADCHF', CADJPY: 'OANDA:CADJPY', CHFJPY: 'OANDA:CHFJPY',
  EURCAD: 'OANDA:EURCAD',

  // ── Metals — OANDA ──
  XAUUSD: 'OANDA:XAUUSD', XAGUSD: 'OANDA:XAGUSD',
  XPTUSD: 'OANDA:XPTUSD', XPDUSD: 'OANDA:XPDUSD',
  XAUEUR: 'OANDA:XAUEUR', XAUAUD: 'OANDA:XAUAUD',
  XAUGBP: 'OANDA:XAUGBP', XAUCHF: 'OANDA:XAUCHF',
  XAUJPY: 'OANDA:XAUJPY', XAGEUR: 'OANDA:XAGEUR',

  // ── Indices / commodities — TVC ──
  USOIL: 'TVC:USOIL',
  US30: 'TVC:DJI',
  US500: 'SP:SPX',
  NAS100: 'NASDAQ:NDX',

  // ── Crypto — COINBASE / BITSTAMP / BINANCE (whichever has the cleanest free feed) ──
  BTCUSD: 'COINBASE:BTCUSD', ETHUSD: 'COINBASE:ETHUSD', LTCUSD: 'COINBASE:LTCUSD',
  XRPUSD: 'BITSTAMP:XRPUSD', BNBUSD: 'BINANCE:BNBUSDT', SOLUSD: 'COINBASE:SOLUSD',
  ADAUSD: 'COINBASE:ADAUSD', DOGEUSD: 'BINANCE:DOGEUSDT', DOGUSD: 'BINANCE:DOGEUSDT',
  DOTUSD: 'COINBASE:DOTUSD', MATICUSD: 'COINBASE:MATICUSD', AVAXUSD: 'COINBASE:AVAXUSD',
  LINKUSD: 'COINBASE:LINKUSD', BCHUSD: 'BINANCE:BCHUSDT', SHIBUSD: 'BINANCE:SHIBUSDT',
  XLMUSD: 'BINANCE:XLMUSDT', TRXUSD: 'BINANCE:TRXUSDT', UNIUSD: 'BINANCE:UNIUSDT',
  ATOMUSD: 'BINANCE:ATOMUSDT', ETCUSD: 'BINANCE:ETCUSDT', FILUSD: 'BINANCE:FILUSDT',
  ICPUSD: 'BINANCE:ICPUSDT', VETUSD: 'BINANCE:VETUSDT', NEARUSD: 'BINANCE:NEARUSDT',
  GRTUSD: 'BINANCE:GRTUSDT', AAVEUSD: 'BINANCE:AAVEUSDT', MKRUSD: 'BINANCE:MKRUSDT',
  ALGOUSD: 'BINANCE:ALGOUSDT', FTMUSD: 'BINANCE:FTMUSDT', SANDUSD: 'BINANCE:SANDUSDT',
  MANAUSD: 'BINANCE:MANAUSDT', AXSUSD: 'BINANCE:AXSUSDT', THETAUSD: 'BINANCE:THETAUSDT',
  XMRUSD: 'BINANCE:XMRUSDT', SNXUSD: 'BINANCE:SNXUSDT', EOSUSD: 'BINANCE:EOSUSDT',
  CHZUSD: 'BINANCE:CHZUSDT', ENJUSD: 'BINANCE:ENJUSDT', PEPEUSD: 'BINANCE:PEPEUSDT',
  ARBUSD: 'BINANCE:ARBUSDT', OPUSD: 'BINANCE:OPUSDT', SUIUSD: 'BINANCE:SUIUSDT',
  APTUSD: 'BINANCE:APTUSDT', INJUSD: 'BINANCE:INJUSDT', TONUSD: 'BINANCE:TONUSDT',
  HBARUSD: 'BINANCE:HBARUSDT',
};

export function toTradingViewSymbol(symbol: string | undefined | null): string {
  const s = (symbol || 'XAUUSD').toUpperCase();
  return TRADINGVIEW_SYMBOL_MAP[s] || `OANDA:${s}`;
}
